name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Test python files
       run: |
         python3 -m py_compile monitor.py
         python3 -m py_compile logger.py

     - name: Build Docker image
       run: docker build -t server-health-monitor .

     - name: Run container
       run: docker run -d --name test-container server-health-monitor

     - name: Check container
       run: docker ps -a
